### ISSUE TITLE
How to do without persistence.xml file?

### ISSUE THREAD

**Issue by kfgisbis** [hantsy/spring-puzzles#10]
https://github.com/hantsy/spring-puzzles/blob/fedafffb4c24696ec093057445960a4f558091f9/hibernate-reactive/src/main/java/com/example/demo/DemoApplication.java#L25C44-L25C44

**Comment by hantsy** [comment]
Have a look at the current EntityManagerFactoryBean implementations, and create a reactive version yourself.
